/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

package studio.core.v1;

import studio.core.v1.model.ActionNode;
import studio.core.v1.model.AudioAsset;
import studio.core.v1.model.ControlSettings;
import studio.core.v1.model.ImageAsset;
import studio.core.v1.model.StageNode;
import studio.core.v1.model.StoryPack;
import studio.core.v1.model.Transition;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 * Story packs built in code, for tests that need a pack rather than a file.
 *
 * <p>Nothing here comes from a device or from anyone's library: the assets are generated byte
 * patterns carrying the mime types the writers require, not real images or audio. That is enough
 * for the formats, which copy asset bytes verbatim and never decode them — {@code BinaryStoryPackWriter}
 * checks {@code image/bmp} and {@code audio/x-wav} and writes whatever bytes it is given.
 *
 * <p>Asset sizes default to whole multiples of {@link Constants#SECTOR_SIZE}. The binary format
 * stores assets in sectors and reads back {@code 512 × sectors} bytes, so an asset whose length is
 * not a multiple of 512 comes back longer than it went in. Tests that want to pin that behaviour ask
 * for it explicitly with {@link #packWithAssetSizes}; the rest stay on sector boundaries so a failed
 * comparison means something went wrong rather than that padding exists.
 */
public final class PackFixtures {

    public static final String UUID = "12345678-1234-1234-1234-123456789abc";

    private PackFixtures() {
    }

    /** A pack with two stage nodes, distinct assets on each, and an action node joining them. */
    public static StoryPack twoStagePack() {
        return packWithAssetSizes(Constants.SECTOR_SIZE, Constants.SECTOR_SIZE * 2);
    }

    /**
     * The same shape, with asset lengths chosen by the caller.
     *
     * @param imageSize bytes of image data on each stage node
     * @param audioSize bytes of audio data on each stage node
     */
    public static StoryPack packWithAssetSizes(int imageSize, int audioSize) {
        StageNode first = stageNode("11111111-1111-1111-1111-111111111111",
                pattern((byte) 0x41, imageSize), pattern((byte) 0x61, audioSize));
        StageNode second = stageNode("22222222-2222-2222-2222-222222222222",
                pattern((byte) 0x42, imageSize), pattern((byte) 0x62, audioSize));

        // One action node, reached from both stage nodes, offering only the second of them.
        //
        // Offering the first as well would be the more obvious fixture and it is deliberately not
        // used here: the binary format addresses options by sector, the first stage node sits at
        // sector 0, and the reader treats 0 as the end of the option list. An option pointing at it
        // therefore truncates the list. That is pinned in its own case by BinaryPackRoundTripTest,
        // and kept out of the general fixture so every other test is not silently exercising it.
        ActionNode action = new ActionNode(new ArrayList<>(Arrays.asList(second)), null);
        first.setOkTransition(new Transition(action, (short) 0));
        first.setHomeTransition(new Transition(action, (short) 0));
        second.setOkTransition(new Transition(action, (short) 0));
        second.setHomeTransition(new Transition(action, (short) 0));

        List<StageNode> nodes = new ArrayList<>(Arrays.asList(first, second));
        return new StoryPack(UUID, false, (short) 1, nodes, null, false);
    }

    /**
     * The same pack, with the action node offering the <em>first</em> stage node as well.
     *
     * <p>Only for the case that pins what the binary format does with it. See
     * {@link #twoStagePack()}.
     */
    public static StoryPack packWithOptionOnFirstNode() {
        StoryPack pack = twoStagePack();
        StageNode first = pack.getStageNodes().get(0);
        StageNode second = pack.getStageNodes().get(1);
        first.getOkTransition().getActionNode()
                .setOptions(new ArrayList<>(Arrays.asList(first, second)));
        return pack;
    }

    private static StageNode stageNode(String uuid, byte[] image, byte[] audio) {
        return new StageNode(
                uuid,
                new ImageAsset("image/bmp", image, uuid + ".bmp"),
                new AudioAsset("audio/x-wav", audio, uuid + ".wav"),
                null,
                null,
                new ControlSettings(true, true, true, false, false),
                null);
    }

    /**
     * Bytes that differ from one another and from padding, so a comparison that passes is not
     * passing because everything is zero.
     */
    public static byte[] pattern(byte seed, int length) {
        byte[] data = new byte[length];
        for (int i = 0; i < length; i++) {
            data[i] = (byte) (seed + (i % 97));
        }
        return data;
    }
}
